languages:
  JavaScript: true
  Python: true

exclude_paths:
- "siteflags/runtests.py"
- "siteflags/tests.py"
- "siteflags/tests/*"
- "siteflags/migrations/*"
- "siteflags/south_migrations/*"
- "docs/*"
